//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MightyCasl.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define CG_IDR_POPUP_WATCH_DLG          103
#define CG_IDR_POPUP_SOURCE_VIEW        104
#define CG_IDR_POPUP_OUTPUT_VIEW        105
#define CG_IDR_POPUP_DUMP_VIEW          108
#define IDR_MAINFRAME                   128
#define IDR_MIGHTYTYPE                  129
#define IDR_SOURCETYPE                  130
#define IDD_REGISTER                    130
#define IDB_ICON_SIMULATE               131
#define CG_IDR_POPUP_SIMULATE_VIEW      131
#define IDB_ICON_STACK                  132
#define IDD_WATCH                       132
#define IDD_ENVIRONMENT                 133
#define IDD_INPUT_DEVICE                134
#define IDD_LICENSE                     135
#define IDS_TEXTFILE_ACCESS_FILTER      200
#define IDS_SOURCEPATHREF_TITLE         800
#define IDS_MSG_ASMCOMPLETE             900
#define IDS_MSG_USERSTOP                901
#define IDS_MSG_EXECUTEXIT              902
#define IDS_MSG_OVERDATE                903
#define IDS_MSG_TRIAL                   904
#define IDS_MSG_OVERDATE_EXIT           905
#define IDS_ERR_ASSEMBLE                1000
#define IDS_ERR_OPENSIMULATORFRAME      1001
#define IDS_ERR_SETREGISTER             1002
#define IDS_ERR_BADWATCHTARGET_NUM      1003
#define IDS_ERR_BADWATCHTARGET_REG      1004
#define IDS_ERR_BADWATCHTARGET_LEN      1005
#define IDS_ERR_BADWATCHTARGET          1006
#define IDS_ERR_OUTFILE_CREATE          1007
#define IDS_ERR_INFILE_OPEN             1008
#define IDS_ERR_INFILE_READ             1009
#define IDS_ERR_OUTFILE_WRITE           1010
#define IDS_ERR_LICENSEKEY              1011
#define IDC_TARGET                      1012
#define IDC_LENGTH                      1013
#define IDC_SPIN_LENGTH                 1014
#define IDC_FMT_HEX                     1015
#define IDC_FMT_SIGNED                  1016
#define IDC_SOURCEPATH                  1016
#define IDC_FMT_UNSIGNED                1017
#define IDC_REF_SOURCEPATH              1017
#define IDC_FMT_BINARY                  1018
#define IDC_WORKVIEW_DUMP               1018
#define IDC_FMT_CHAR                    1019
#define IDC_WORKVIEW_WATCH              1019
#define IDC_WORKVIEW_DUMP3              1020
#define IDC_SAVE_WATCH                  1021
#define IDC_IN_CONSOLE                  1022
#define IDC_IN_FILE                     1023
#define IDC_EDIT                        1023
#define IDC_IN_FILENAME                 1024
#define IDC_REF_INFILE                  1025
#define IDC_VERSION                     1025
#define IDC_OUT_CONSOLE                 1026
#define IDC_SUBMSG                      1026
#define IDC_OUT_FILE                    1027
#define IDC_ID                          1027
#define IDC_OUT_FILENAME                1028
#define IDC_KEY                         1028
#define IDC_FR_OVERFLOW                 1028
#define IDC_REF_OUTFILE                 1029
#define IDC_FR_SIGN                     1029
#define IDC_GR0                         1100
#define IDC_GR1                         1101
#define IDC_GR2                         1102
#define IDC_GR3                         1103
#define IDC_GR4                         1104
#define IDC_GR5                         1105
#define IDC_GR6                         1106
#define IDC_GR7                         1107
#define IDC_PC                          1108
#define IDC_SP                          1109
#define IDC_FR_PLUS                     1110
#define IDC_FR_ZERO                     1111
#define IDC_FR_MINUS                    1112
#define IDS_ASMERR_NO_MNEMONIC          2000
#define IDS_ASMERR_LABEL_TOOLONG        2001
#define IDS_ASMERR_LABEL_MULTIDEF       2002
#define IDS_ASMERR_LABEL_BADFIRSTCHAR   2003
#define IDS_ASMERR_LABEL_BADCHAR        2004
#define IDS_ASMERR_OPE_BADLABEL         2005
#define IDS_ASMERR_OPE_UNDEF_LABEL      2006
#define IDS_ASMERR_BADMNEMONIC          2007
#define IDS_ASMERR_ILLEGAL_START        2008
#define IDS_ASMERR_OPE_SPACE            2009
#define IDS_ASMERR_OPE_NOTHING          2010
#define IDS_ASMERR_OPE_BADSTRFMT        2011
#define IDS_ASMERR_OPE_NULLSTR          2012
#define IDS_ASMERR_OPE_BADHEXFMT        2013
#define IDS_ASMERR_OPE_BADDIGITFMT      2014
#define IDS_ASMERR_OPE_MUSTBEPLUS       2015
#define IDS_ASMERR_OPE_NUMBER           2016
#define IDS_ASMERR_OPE_FORMAT1ERR       2017
#define IDS_ASMERR_OPE_FORMAT2ERR       2018
#define IDS_ASMERR_OPE_FORMAT3ERR       2019
#define IDS_ASMERR_OPE_BADDIGITFMT2     2020
#define IDS_ASMERR_OPE_BADLABEL2        2021
#define IDS_ASMERR_OPE_UNDEF_LABEL2     2022
#define IDS_ASMERR_OPE_BADDIGITFMT1     2023
#define IDS_ASMERR_OPE_BADLABEL1        2024
#define IDS_ASMERR_OPE_UNDEF_LABEL1     2025
#define IDS_ASMERR_OPE_FORMATERR        2026
#define IDS_ASMERR_MULTI_START          2027
#define IDS_ASMERR_NOSTART              2028
#define IDS_ASMERR_NOEND                2029
#define IDS_ASMERR_NULLSTR              2030
#define IDS_ASMERR_LABEL_GRX            2031
#define IDS_ASMERR_OPE_BAD_LITERAL      2032
#define IDS_ASMERR_MULTI_END            2033
#define IDS_RUNERR_NOEXECUTABLE         2100
#define IDS_RUNERR_CODECHANGED          2101
#define IDS_ASMERR_LIT_NOTHING          2910
#define IDS_ASMERR_LIT_BADSTRFMT        2911
#define IDS_ASMERR_LIT_NULLSTR          2912
#define IDS_ASMERR_LIT_BADHEXFMT        2913
#define IDS_ASMERR_LIT_BADDIGITFMT      2914
#define ID_TOOL_ASM                     32771
#define ID_BREAKPOINT_SET               32772
#define ID_BREAKPOINT_CLEAR             32773
#define ID_BREAKPOINT_ALLCLEAR          32774
#define ID_REGISTER_SET                 32775
#define ID_EXECUTE_PASS                 32776
#define ID_EXECUTE_TRACE                32777
#define ID_EXECUTE_COME                 32778
#define ID_EXECUTE_GO                   32779
#define ID_REGISTER_PC                  32780
#define ID_EXEC_RELOAD                  32782
#define ID_EXECUTE_RELOAD               32783
#define ID_EXEXUTE_STOP                 32790
#define ID_INDICATOR_CARET              32794
#define ID_INDICATOR_PROGRESS           32795
#define ID_WORKVIEW_DUMP                32796
#define ID_WORKVIEW_WATCH               32797
#define ID_WORKVIEW_OUTPUT              32798
#define ID_WATCH_NEW                    32799
#define ID_WATCH_CLEAR                  32800
#define ID_WATCH_MODIFY                 32801
#define ID_TOOL_ENV                     32805
#define ID_HELP_SUPPORT                 32806
#define ID_HELP_DOCUMNET                32807
#define ID_TOOL_LISENCE                 32808

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
